language: node_js
node_js:
  - "10"

services:
  - docker

install:
  - docker build -t ifad/backend .
  - docker run -d -p 127.0.0.1:80:4567 ifad/backend
  - npm install

script:
  - yarn test

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      docker push nicholastmosher/ifad-backend ;
    fi
