language: node_js
node_js:
  - "10"

services:
  - docker

branches:
  only:
    - master
    - add_travis

install:
  - docker build -t npm/lts .
  - docker run -d -p 127.0.0.1:80:4567 npm/lts
  - npm i jest
  - npm install --save-dev jest typescript ts-jest @types/jest

script:
  - yarn test
