import {parseAnnotationsData, parseAnnotationsText, parseGenesData, splitMetadataText} from "../ingest";

const gene_data = `
AT1G01010	protein_coding
AT1G01020	protein_coding
AT1G01030	protein_coding
AT1G01040	protein_coding
AT1G01046	miRNA_primary_transcript
AT1G01050	protein_coding
AT1G01060	protein_coding
AT1G01070	protein_coding
AT1G01080	protein_coding
AT1G01090	protein_coding
`;

const annotation_data = `
TAIR	locus:2079747	ALY2		GO:0000003	TAIR:Communication:501741973	IBA	PANTHER:PTN000495591|WB:WBGene00002998	P	AT3G05380	AT3G05380|ALY2|ATALY2|ALWAYS EARLY 2|ARABIDOPSIS THALIANA ALWAYS EARLY 2|F22F7.18|F22F7_18	protein	taxon:3702	20180615	GOC		TAIR:locus:2079747
TAIR	locus:2089438	ALY3		GO:0000003	TAIR:Communication:501741973	IBA	PANTHER:PTN000495591|WB:WBGene00002998	P	AT3G21430	AT3G21430|ATALY3|ALY3|ARABIDOPSIS THALIANA ALWAYS EARLY 3|ALWAYS EARLY 3	protein	taxon:3702	20180615	GOC		TAIR:locus:2089438
TAIR	locus:2143666	ALY1		GO:0000003	TAIR:Communication:501741973	IBA	PANTHER:PTN000495591|WB:WBGene00002998	P	AT5G27610	AT5G27610|ATALY1|ALY1|ARABIDOPSIS THALIANA ALWAYS EARLY 1|ALWAYS EARLY 1|F15A18.70|F15A18_70	protein	taxon:3702	20180615	GOC		TAIR:locus:2143666
TAIR	locus:2179122	APTX		GO:0000012	TAIR:Communication:501741973	IBA	PANTHER:PTN000281062|MGI:MGI:1913658|UniProtKB:Q7Z2E3	P	AT5G01310	AT5G01310|APTX|APRATAXIN-like|T10O8.20|T10O8_20	protein	taxon:3702	20180803	GOC		TAIR:locus:2179122
TAIR	locus:2150931	TDP1		GO:0000012	TAIR:Communication:501741973	IBA	PANTHER:PTN000275870|MGI:MGI:1920036|UniProtKB:Q9NUW8	P	AT5G15170	AT5G15170|TDP1|tyrosyl-DNA phosphodiesterase 1|F8M21.60|F8M21_60	protein	taxon:3702	20180803	GOC		TAIR:locus:2150931
TAIR	locus:2202114	BFN1		GO:0000014	TAIR:Communication:501741973	IBA	PANTHER:PTN002107734|TAIR:locus:2202114	F	AT1G11190	AT1G11190|BFN1|ENDO1|bifunctional nuclease i|ENDONUCLEASE 1|T28P6.14|T28P6_14	protein	taxon:3702	20180615	GOC		TAIR:locus:2202114
TAIR	locus:2045437	RAD50		GO:0000014	TAIR:Communication:501741973	IBA	PANTHER:PTN000429848|UniProtKB:Q92878	F	AT2G31970	AT2G31970|RAD50|ATRAD50|F22D22.28|F22D22_28|dna repair-recombination protein	protein	taxon:3702	20180630	GOC		TAIR:locus:2045437
TAIR	locus:2096329	ERCC1		GO:0000014	TAIR:Communication:501741973	IBA	PANTHER:PTN000297520|UniProtKB:P07992|SGD:S000004560	F	AT3G05210	AT3G05210|ERCC1|UVR7|UV REPAIR DEFICIENT 7|T12H1.18|T12H1_18	protein	taxon:3702	20180803	GOC		TAIR:locus:2096329
TAIR	locus:1005716561	GR1		GO:0000014	TAIR:Communication:501741973	IBA	PANTHER:PTN000387514|UniProtKB:Q99708	F	AT3G52115	AT3G52115|ATGR1|ATCOM1|COM1|GR1|gamma response gene 1	protein	taxon:3702	20180615	GOC		TAIR:locus:1005716561
TAIR	locus:2163011	UVH1		GO:0000014	TAIR:Communication:501741973	IBA	PANTHER:PTN000015911|UniProtKB:Q9LKI5|SGD:S000005943	F	AT5G41150	AT5G41150|UVH1|ATRAD1|RAD1|ULTRAVIOLET HYPERSENSITIVE 1|MEE6.22|MEE6_22|repair endonuclease	protein	taxon:3702	20180615	GOC		TAIR:locus:2163011
`;

describe("Ingestion functions", () => {

    it("should parse a set of Annotations", () => {
        expect(parseAnnotationsData(annotation_data)).toMatchSnapshot();
    });

    it("should parse a set of Gene IDs and Gene Product Types", () => {
        expect(parseGenesData(gene_data)).toMatchSnapshot();
    });

    it("should not fail if the input text is empty", () => {
        expect(() => parseGenesData("")).not.toThrow();
    });
});

describe("The Annotation text parser", () => {

  it("should separate metadata from annotation data", () => {
    const raw_annotation_text = `!gaf-version: 2.1
!
!Generated by GO Central
!
!Date Generated by GOC: 2019-10-07
!
!Header from tair source association file:
!=================================
!Project_name: The Arabidopsis Information Resource (TAIR)
!URL: http://www.arabidopsis.org
!Contact Email: curator@arabidopsis.org
!Last Updated: 2019-10-01
!=================================
!
!Header copied from paint_tair_valid.gaf
!=================================
!Created on Tue Jul 23 20:16:17 2019.
!PANTHER version: v.14.1.
!GO version: 2019-07-03.
!
!=================================
!
!Documentation about this header can be found here: https://github.com/geneontology/go-site/blob/master/docs/gaf_validation.md
!
DB	DB Object ID	DB Object Symbol	Qualifier	GO ID	DB:Reference (JDB:Reference)	Evidence Code	With (or) From	Aspect	DB Object Name	DB Object Type	Taxon	Date	Assigned By	Annotation Extension	Gene Product Form ID
TAIR	locus:2031476	ENO1		GO:0000015	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR000941	C	AT1G74030	AT1G74030|ENO1|enolase 1|F2P9.10|F2P9_10	protein	taxon:3702	20190907	InterPro		TAIR:locus:2031476
TAIR	locus:2043067	ENOC		GO:0000015	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR000941	C	AT2G29560	AT2G29560|ENOC|ENO3|cytosolic enolase|enolase 3|F16P2.6|F16P2_6	protein	taxon:3702	20190408	InterPro		TAIR:locus:2043067
TAIR	locus:2044851	LOS2		GO:0000015	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR000941	C	AT2G36530	AT2G36530|LOS2|ENO2|LOW EXPRESSION OF OSMOTICALLY RESPONSIVE GENES 2|enolase 2|F1O11.16|F1O11_16	protein	taxon:3702	20190408	InterPro		TAIR:locus:2044851
TAIR	locus:2032970	AT1G25260		GO:0000027	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR033867	P	AT1G25260	AT1G25260|F4F7.35|F4F7_35	protein	taxon:3702	20190404	InterPro		TAIR:locus:2032970
TAIR	locus:2017963	TUN		GO:0000030	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR026051	F	AT1G16570	AT1G16570|TUN|TURAN|F19K19.11|F19K19_11	protein	taxon:3702	20190907	InterPro		TAIR:locus:2017963
TAIR	locus:2011962	ALATS		GO:0000049	TAIR:AnalysisReference:501756968	IEA	UniProtKB-KW:KW-0820	F	AT1G50200	AT1G50200|ALATS|ACD|Alanyl-tRNA synthetase|F14I3.17|F14I3_17|ALARS	protein	taxon:3702	20190327	UniProt		TAIR:locus:2011962
TAIR	locus:2064821	CTEXP		GO:0000049	TAIR:Publication:501746929	IDA		F	AT2G40730	AT2G40730|CTEXP|cytoplasmic tRNA export protein|T7D17.9|T7D17_9	protein	taxon:3702	20120106	TAIR		TAIR:locus:2064821
TAIR	locus:2074552	TRM1a		GO:0000049	TAIR:AnalysisReference:501756968	IEA	UniProtKB-KW:KW-0820	F	AT3G02320	AT3G02320|TRM1a|AtTRM1a|tRNA methyltransferase 1a|F11A12.1|F11A12_1	protein	taxon:3702	20190907	UniProt		TAIR:locus:2074552
TAIR	locus:2085455	AT3G58140		GO:0000049	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR002319	F	AT3G58140	AT3G58140|F9D24.50	protein	taxon:3702	20190907	InterPro		TAIR:locus:2085455
TAIR	locus:2081217	GCN2		GO:0000049	TAIR:AnalysisReference:501756968	IEA	UniProtKB-KW:KW-0820	F	AT3G59410	AT3G59410|ATGCN2|GCN2|ARABIDOPSIS THALIANA GENERAL CONTROL NON-REPRESSIBLE 2|GENERAL CONTROL NON-REPRESSIBLE 2|F25L23.270	protein	taxon:3702	20190907	UniProt		TAIR:locus:2081217
TAIR	locus:2119515	AT4G13780		GO:0000049	TAIR:AnalysisReference:501756968	IEA	UniProtKB-KW:KW-0820	F	AT4G13780	AT4G13780|F18A5.170|F18A5_170	protein	taxon:3702	20181101	UniProt		TAIR:locus:2119515
TAIR	locus:2124519	AT4G18460		GO:0000049	TAIR:AnalysisReference:501756970	IEA	UniProtKB-KW:KW-0820	F	AT4G18460	AT4G18460|F28J12.130	protein	taxon:3702	20190410	UniProt		TAIR:locus:2124519
TAIR	locus:2125359	CTU2		GO:0000049	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR019407	F	AT4G35910	AT4G35910|CTU2|CYTOPLASMIC THIOURIDYLASE 2|T19K4.40	protein	taxon:3702	20190601	InterPro		TAIR:locus:2125359
TAIR	locus:2136328	AT4G39280		GO:0000049	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR002319	F	AT4G39280	AT4G39280|T22F8.180|T22F8_180	protein	taxon:3702	20190907	InterPro		TAIR:locus:2136328
TAIR	locus:2143266	TRM1b		GO:0000049	TAIR:AnalysisReference:501756968	IEA	UniProtKB-KW:KW-0820	F	AT5G15810	AT5G15810|TRM1b|AtTRM1b|tRNA methyltransferase 1b|F14F8.190|F14F8_190	protein	taxon:3702	20190907	UniProt		TAIR:locus:2143266`;

    const result = splitMetadataText(raw_annotation_text);
    if (!result) fail("test data should split correctly");
    const { metadataText, bodyText } = result;

    const expected_metadata = `!gaf-version: 2.1
!
!Generated by GO Central
!
!Date Generated by GOC: 2019-10-07
!
!Header from tair source association file:
!=================================
!Project_name: The Arabidopsis Information Resource (TAIR)
!URL: http://www.arabidopsis.org
!Contact Email: curator@arabidopsis.org
!Last Updated: 2019-10-01
!=================================
!
!Header copied from paint_tair_valid.gaf
!=================================
!Created on Tue Jul 23 20:16:17 2019.
!PANTHER version: v.14.1.
!GO version: 2019-07-03.
!
!=================================
!
!Documentation about this header can be found here: https://github.com/geneontology/go-site/blob/master/docs/gaf_validation.md
!
`;
    expect(metadataText).toEqual(expected_metadata);

    const expected_annotations = `DB	DB Object ID	DB Object Symbol	Qualifier	GO ID	DB:Reference (JDB:Reference)	Evidence Code	With (or) From	Aspect	DB Object Name	DB Object Type	Taxon	Date	Assigned By	Annotation Extension	Gene Product Form ID
TAIR	locus:2031476	ENO1		GO:0000015	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR000941	C	AT1G74030	AT1G74030|ENO1|enolase 1|F2P9.10|F2P9_10	protein	taxon:3702	20190907	InterPro		TAIR:locus:2031476
TAIR	locus:2043067	ENOC		GO:0000015	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR000941	C	AT2G29560	AT2G29560|ENOC|ENO3|cytosolic enolase|enolase 3|F16P2.6|F16P2_6	protein	taxon:3702	20190408	InterPro		TAIR:locus:2043067
TAIR	locus:2044851	LOS2		GO:0000015	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR000941	C	AT2G36530	AT2G36530|LOS2|ENO2|LOW EXPRESSION OF OSMOTICALLY RESPONSIVE GENES 2|enolase 2|F1O11.16|F1O11_16	protein	taxon:3702	20190408	InterPro		TAIR:locus:2044851
TAIR	locus:2032970	AT1G25260		GO:0000027	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR033867	P	AT1G25260	AT1G25260|F4F7.35|F4F7_35	protein	taxon:3702	20190404	InterPro		TAIR:locus:2032970
TAIR	locus:2017963	TUN		GO:0000030	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR026051	F	AT1G16570	AT1G16570|TUN|TURAN|F19K19.11|F19K19_11	protein	taxon:3702	20190907	InterPro		TAIR:locus:2017963
TAIR	locus:2011962	ALATS		GO:0000049	TAIR:AnalysisReference:501756968	IEA	UniProtKB-KW:KW-0820	F	AT1G50200	AT1G50200|ALATS|ACD|Alanyl-tRNA synthetase|F14I3.17|F14I3_17|ALARS	protein	taxon:3702	20190327	UniProt		TAIR:locus:2011962
TAIR	locus:2064821	CTEXP		GO:0000049	TAIR:Publication:501746929	IDA		F	AT2G40730	AT2G40730|CTEXP|cytoplasmic tRNA export protein|T7D17.9|T7D17_9	protein	taxon:3702	20120106	TAIR		TAIR:locus:2064821
TAIR	locus:2074552	TRM1a		GO:0000049	TAIR:AnalysisReference:501756968	IEA	UniProtKB-KW:KW-0820	F	AT3G02320	AT3G02320|TRM1a|AtTRM1a|tRNA methyltransferase 1a|F11A12.1|F11A12_1	protein	taxon:3702	20190907	UniProt		TAIR:locus:2074552
TAIR	locus:2085455	AT3G58140		GO:0000049	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR002319	F	AT3G58140	AT3G58140|F9D24.50	protein	taxon:3702	20190907	InterPro		TAIR:locus:2085455
TAIR	locus:2081217	GCN2		GO:0000049	TAIR:AnalysisReference:501756968	IEA	UniProtKB-KW:KW-0820	F	AT3G59410	AT3G59410|ATGCN2|GCN2|ARABIDOPSIS THALIANA GENERAL CONTROL NON-REPRESSIBLE 2|GENERAL CONTROL NON-REPRESSIBLE 2|F25L23.270	protein	taxon:3702	20190907	UniProt		TAIR:locus:2081217
TAIR	locus:2119515	AT4G13780		GO:0000049	TAIR:AnalysisReference:501756968	IEA	UniProtKB-KW:KW-0820	F	AT4G13780	AT4G13780|F18A5.170|F18A5_170	protein	taxon:3702	20181101	UniProt		TAIR:locus:2119515
TAIR	locus:2124519	AT4G18460		GO:0000049	TAIR:AnalysisReference:501756970	IEA	UniProtKB-KW:KW-0820	F	AT4G18460	AT4G18460|F28J12.130	protein	taxon:3702	20190410	UniProt		TAIR:locus:2124519
TAIR	locus:2125359	CTU2		GO:0000049	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR019407	F	AT4G35910	AT4G35910|CTU2|CYTOPLASMIC THIOURIDYLASE 2|T19K4.40	protein	taxon:3702	20190601	InterPro		TAIR:locus:2125359
TAIR	locus:2136328	AT4G39280		GO:0000049	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR002319	F	AT4G39280	AT4G39280|T22F8.180|T22F8_180	protein	taxon:3702	20190907	InterPro		TAIR:locus:2136328
TAIR	locus:2143266	TRM1b		GO:0000049	TAIR:AnalysisReference:501756968	IEA	UniProtKB-KW:KW-0820	F	AT5G15810	AT5G15810|TRM1b|AtTRM1b|tRNA methyltransferase 1b|F14F8.190|F14F8_190	protein	taxon:3702	20190907	UniProt		TAIR:locus:2143266`;
    expect(bodyText).toEqual(expected_annotations);

  });

  it("should capture blank lines as part of the metadata", () => {
    const raw_annotation_text = `


!gaf-version: 2.1
!


!Generated by GO Central


!
!Date Generated by GOC: 2019-10-07


DB	DB Object ID	DB Object Symbol	Qualifier	GO ID	DB:Reference (JDB:Reference)	Evidence Code	With (or) From	Aspect	DB Object Name	DB Object Type	Taxon	Date	Assigned By	Annotation Extension	Gene Product Form ID
TAIR	locus:2031476	ENO1		GO:0000015	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR000941	C	AT1G74030	AT1G74030|ENO1|enolase 1|F2P9.10|F2P9_10	protein	taxon:3702	20190907	InterPro		TAIR:locus:2031476
TAIR	locus:2043067	ENOC		GO:0000015	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR000941	C	AT2G29560	AT2G29560|ENOC|ENO3|cytosolic enolase|enolase 3|F16P2.6|F16P2_6	protein	taxon:3702	20190408	InterPro		TAIR:locus:2043067
TAIR	locus:2044851	LOS2		GO:0000015	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR000941	C	AT2G36530	AT2G36530|LOS2|ENO2|LOW EXPRESSION OF OSMOTICALLY RESPONSIVE GENES 2|enolase 2|F1O11.16|F1O11_16	protein	taxon:3702	20190408	InterPro		TAIR:locus:2044851
TAIR	locus:2032970	AT1G25260		GO:0000027	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR033867	P	AT1G25260	AT1G25260|F4F7.35|F4F7_35	protein	taxon:3702	20190404	InterPro		TAIR:locus:2032970`;

    const result = splitMetadataText(raw_annotation_text);
    if (!result) fail("test data should split correctly");
    const { metadataText, bodyText } = result;

    const expected_metadata = `


!gaf-version: 2.1
!


!Generated by GO Central


!
!Date Generated by GOC: 2019-10-07


`;

    expect(metadataText).toEqual(expected_metadata);

    const expected_annotations = `DB	DB Object ID	DB Object Symbol	Qualifier	GO ID	DB:Reference (JDB:Reference)	Evidence Code	With (or) From	Aspect	DB Object Name	DB Object Type	Taxon	Date	Assigned By	Annotation Extension	Gene Product Form ID
TAIR	locus:2031476	ENO1		GO:0000015	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR000941	C	AT1G74030	AT1G74030|ENO1|enolase 1|F2P9.10|F2P9_10	protein	taxon:3702	20190907	InterPro		TAIR:locus:2031476
TAIR	locus:2043067	ENOC		GO:0000015	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR000941	C	AT2G29560	AT2G29560|ENOC|ENO3|cytosolic enolase|enolase 3|F16P2.6|F16P2_6	protein	taxon:3702	20190408	InterPro		TAIR:locus:2043067
TAIR	locus:2044851	LOS2		GO:0000015	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR000941	C	AT2G36530	AT2G36530|LOS2|ENO2|LOW EXPRESSION OF OSMOTICALLY RESPONSIVE GENES 2|enolase 2|F1O11.16|F1O11_16	protein	taxon:3702	20190408	InterPro		TAIR:locus:2044851
TAIR	locus:2032970	AT1G25260		GO:0000027	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR033867	P	AT1G25260	AT1G25260|F4F7.35|F4F7_35	protein	taxon:3702	20190404	InterPro		TAIR:locus:2032970`;

    expect(bodyText).toEqual(expected_annotations);
  });

  it("should remove headers from annotations files", () => {

    const annotations_file = `
!Generated by GO Central
!
!Date Generated by GOC: 2019-10-07
DB	DB Object ID	DB Object Symbol	Qualifier	GO ID	DB:Reference (JDB:Reference)	Evidence Code	With (or) From	Aspect	DB Object Name	DB Object Type	Taxon	Date	Assigned By	Annotation Extension	Gene Product Form ID
TAIR	locus:2031476	ENO1		GO:0000015	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR000941	C	AT1G74030	AT1G74030|ENO1|enolase 1|F2P9.10|F2P9_10	protein	taxon:3702	20190907	InterPro		TAIR:locus:2031476
TAIR	locus:2043067	ENOC		GO:0000015	TAIR:AnalysisReference:501756966	IEA	InterPro:IPR000941	C	AT2G29560	AT2G29560|ENOC|ENO3|cytosolic enolase|enolase 3|F16P2.6|F16P2_6	protein	taxon:3702	20190408	InterPro		TAIR:locus:2043067`;

    const result = parseAnnotationsText(annotations_file);
    if (!result) fail("annotations should parse");
    const headerExists = result.records.some(annotation =>
      annotation.get("Db") === "DB" ||
      annotation.get("DatabaseID") === "DB Object ID");
    expect(headerExists).toEqual(false);
  });

});
