name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build and test backend
      run: "yarn && yarn test"

    - name: Build docker container and push
      uses: elgohr/Publish-Docker-Github-Action@2.7
      with:
        name: nicholastmosher/ifad-backend
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
